from . import (
    alacritty,
    bash,
    colors,
    fastfetch,
    fish,
    hyprland,
    i3,
    kitty,
    nvim,
    picom,
    polybar,
    rofi,
    tmux,
    wallpaper,
    waybar,
)

modules = {
    "colors": colors.parse_colors,
    "i3": i3.parse_i3,
    "wallpaper": wallpaper.parse_wallpaper,
    "bash": bash.parse_bash,
    "fish": fish.parse_fish,
    "hyprland": hyprland.parse_hyprland,
    "polybar": polybar.parse_polybar,
    "waybar": waybar.parse_waybar,
    "nvim": nvim.parse_nvim,
    "tmux": tmux.parse_tmux,
    "rofi": rofi.parse_rofi,
    "picom": picom.parse_picom,
    "kitty": kitty.parse_kitty,
    "alacritty": alacritty.parse_alacritty,
    "fastfetch": fastfetch.parse_fastfetch,
}
