colors:
  template_path: ""
  destination_path: ""

wallpaper:
  template_path: ""
  destination_path: ""

i3:
  template_path: 'default_configs/i3'
  destination_path: 'i3/'
  config_path: '.config/i3/'

